### ISSUE TITLE
목록 화면에서 검색

### ISSUE THREAD

**Issue by red112** [Code-for-Korea/sanjae.server#10]
질병명으로 검색을 요청하셨는데 그냥 일반 문자열 검색으로 질병명 컬럼과 판결문 컬럼을 대상으로 하는게 좋을듯.

**Comment by happycastle114** [comment]
- [ ] 검색 기능 구현

**Comment by red112** [comment]
구현 잘 되어 있고, 작동 잘 되는 것 확인 했어요. 
감사합니다.! Close 할께요.
