### ISSUE TITLE
최종 수정 정보 표시하기

### ISSUE THREAD

**Issue by red112** [Code-for-Korea/sanjae.server#13]
최종 수정 일시와 최종 수정 계정 표시
위치는 질병코드와 질병명 속성 두 개가 하나로 합쳐져서 남은 곳을 활용하면 될 듯.

**Comment by achimkoh** [comment]
django-model-utils 같은 것을 활용할 수 있을 것 같습니다. 

https://django-model-utils.readthedocs.io/en/latest/utilities.html#field-tracker

**Comment by achimkoh** [comment]
django 기본 기능으로도 할 수 있을 것 같습니다 ㅋㅋ

**Comment by red112** [comment]
좀 고민이 되었던 것이... 상대적으로 쉬운 개발을 '새로 오신 분들이 참여했다는 성취감을 느끼고, 소속감을 느끼면서 동기 부여를 할 수 있는 까치밥

**Comment by achimkoh** [comment]
네 기여하는 방법을 조금 더 친절하게 설명할 필요가 있겠다는 생각이 듭니다. 밋앤핵에서 더 말씀 나눠 봐요!

**Comment by red112** [comment]
이것도 구현 되어 있으니 일단 Close 해 둘께요. 
개선 요청이 있으면 그때 다시 별도 이슈 혹은 reopen하고.
애초에 구체적 요구사항이 없으니 이 정도면 충분히 요구사항을 만족하고 있다고 생각됩니다. ^^
