### ISSUE TITLE
Case App Model에 작성 된 Todo 검토 의견 입니다.

### ISSUE THREAD

**Issue by red112** [Code-for-Korea/sanjae.server#2]
아래 내용을 요약하면...
개발 내용은 개발자가 개발하기 편한 것으로, 법적인 내용이나 의학적 내용은 전문가의 자문을 받되, 우선은 개발하기 편리한 것을 기준으로 하시죠.

1.  **TODO 앱 이름과 모델 이름을 구분하는 게 좋지 않을까..**
- 매 건 이런 의문을 가지고 진행하시면 정신 건강에 좋지 않으니, naming은 편하신 것을 쓰시면 좋겠습니다. 
- naming이라는 것이 각자의 오랜 습관에 영향을 많이 받으니, 코드 작성자가 가장 편한 것을 쓰는 것이 정답일 것 같고, 협업을 해야 할 경우, 필요한 부분은 잘 문서로 정리 해 두면 될 것 같습니다. 개발하기 편하신 것으로 하시죠.

2. **연관사건이 ForeignKey가 될 수 있을까? 현재 목록에 없는 사건번호도 있어서 일괄적용은 어려울 듯.**
- 연관 사건은 최대 5개까지 있었어요. 제가 django를 아직 잘 모르는데, ForeignKey도 동적인 배열로 가져갈 수 있다면 ForeignKey로 가도 좋겠네요.
- 말씀하신 것 처럼, 목록에 있는 것도 있고 없는 것도 있으니, 목록에 있는 연관사건과 목록에 없는 연관 사건을 구분하면 어떨까요? 목록에 없는 연관 사건은 DB update 후, 체크 로직을 반영하고. 
- 목록에 있는 것은 링크가 반영되고, 없는 것은 dimmed처리 되거나 링크 없이 텍스트 그대로 보여주도록 하시죠.

3. 사건연도 분리
- 어디에 나오는 사건 연도를 말씀하시는지요? 
- 사건번호는 그 자체로 고유한 코드라서 이 값으로 법원의 사건정보를 조회하니 이 값은 그대로 유지하는 것이 좋을 것 같아요.
- 연도 속성이 필요하면 사건번호 필터링으로 하거나 별도 속성 추가하는 것이 어떨까요?

4. 법원 이름 띄어쓰기 다른 케이스 존재. 통일
- 법원 이름은 공백을 다 삭제하는 것으로 통일하면 어떨까요?

5. 법원이 별도 테이블로 존재해야 하는가?
- 그럴 필요는 없을 것 같아요.
- 나중에 검색이나 가공을 위한 상세 속성 고도화를 따로 진행하는 것이 좋을 것 같아요. 그때 이야기를 하려면 뭔가 눈에 보이는 것이 있어야 할테니, 우선은 먼저 눈에 보이는 것 만드는 것을 목표로 하고, 구현하시기 용이한 것을 기준으로 하시죠.

**Comment by achimkoh** [comment]
저는 todo를 산만한 메모에 가까운 개념으로 쓰고 있는데.. 세심히 피드백 주셔서 감사합니다. 우선 법원명 공백은 삭제하는 방향으로 https://github.com/achimkoh/sanjae.crawler 이쪽에서 작업하고 있습니다-

**Comment by red112** [comment]
여러가지 고민을 많이 하면서 처리 해 주셔서 감사합니다. 
우리가 돈 받고 하는 일이 아니고, 좋아서 하는 일인만큼 
판단의 기준을 "개발하기 편한 방법"으로 진행하시면 좋겠어요.^^
