### ISSUE TITLE
Working Conditions도 TextField로 하는 것이 좋겠습니다.

### ISSUE THREAD

**Issue by red112** [Code-for-Korea/sanjae.server#3]
만들어 두신 코드를 실행 해 봤는데, 크게 많이 손볼 곳 없이 잘 되어 있는 것 같습니다.
Working conditions는 제가 CharField로 처음에 작성했는데, 제가 실수했어요.
근무조건과 업무 환경은 근로자가 근무한 내용이나 환경에 대한 서술이 필요한 것이라 TextField가 맞을 것 같습니다.

**Comment by red112** [comment]
제가 수정 할까 하다가 혹시 한참 작업 중이신데 오히려 방해(conflict 유발같은...)가 될까 염려되어 수정하지 않았어요.
함께 나눠서 할 일 편히 말씀 해 주세요~

 admin 아닌, 일반 사용자들이 로그인 볼 수 있는 리스트뷰나 Detail뷰 같은 것도 좋고~

**Comment by achimkoh** [comment]
넵. 반영해두었습니다!
